listen_port = 8888                     # Listen on this port
results_port = 8000                    # Serve results at this port
post_to_url = "http://localhost:9000"  # Post JSON to this URL

ping_address = "/ping"                 # Default device OSC address to ping
ping_port = 8888                       # Default device OSC port
ping_delay_sec = 60                    # How often to ping, in seconds

[[devices]]
host = "localhost"  # Only host is required; other fields are optional
name = "sword"
ping_port = 7001

[[devices]]
host = "localhost"
name = "shield"
ping_port = 7002
